### ISSUE TITLE
What about Vue in runtime only mode (no compiler)

### ISSUE THREAD

**Issue by nash403** [viktorlarsson/vue-tiny-slider#11]
Hello !

Could you please replace the template property of your `VueTinySlider ` object with a render function like the following one, so that it could work in a runtime only Vue environment :) would be great !

render fn:
```js
render: function(h){
  return h('div', this.$slots.default)
}
```

Thanks !

See:
https://github.com/viktorlarsson/vue-tiny-slider/blob/7a916f5d77640cd9382ce5ca29836126cfa4a5bf/src/index.js#L159

**Comment by viktorlarsson** [comment]
Could you try it now @nash403 ?

**Comment by nash403** [comment]
works great ! thank you :)
