### ISSUE TITLE
How to use the methods in vue

### ISSUE THREAD

**Issue by DannyPickering** [viktorlarsson/vue-tiny-slider#12]
Can you provide an example on how to use the getInfo method? I need to keep track of the current slide number out of the total slides. (ie: 1/4) Or would I need to wait till events are added?

**Comment by l0r5** [comment]
I struggled with the same problem and solved it with using 'ref':

`<vue-tiny-slider ref="tinySlider" :mouse-drag="true" :loop="false" items="1" gutter="20" tag="div" class="image-container">
        <div>...</div>
</vue-tiny-slider>`

`<script>
import VueTinySlider from 'vue-tiny-slider';

export default {
  ...,
    methods: {
        getInfo: function(event) {
             this.$refs.tinySlider.slider.getInfo();
        }
     }
}`

I hope this could help you :)

**Comment by viktorlarsson** [comment]
Closing this due thanks to @l0r5 !
