### ISSUE TITLE
gutter-option ignored

### ISSUE THREAD

**Issue by piccard21** [viktorlarsson/vue-tiny-slider#19]
Could it be, that the **gutter**-option is being ignored?

**Comment by viktorlarsson** [comment]
Seems like you are right, i'll look into it

**Comment by viktorlarsson** [comment]
Well, the gutter option is not ignored but tiny-slider seems to set the gutter value to padding-right on each item as you can see in the screenshot. It should be margin but on the demo, they seem to create .. margin between each item using.. padding?

![image](https://user-images.githubusercontent.com/722315/40543967-d725216c-6026-11e8-88ff-7620a72784e6.png)
