### ISSUE TITLE
How can I reinit slider?

### ISSUE THREAD

**Issue by Suruat** [viktorlarsson/vue-tiny-slider#24]
I have computed property that on condition filtering slides, but slider do not rerender. I've tried to make it work with this.$refs.carousel.slider.destroy() and this.$refs.carousel.slider.rebuild() after computed property revaluated, but it did not help. Slider rebuilds with initial slides.

I've also tried to make it work with $forceUpdate of slider... no luck either.

Maybe you know a proper way to do such changes? Thank you in advance for your response.

**Comment by viktorlarsson** [comment]
@rymdkapten Didn't we do this in our project?

**Comment by TitanFighter** [comment]
Confirm. Initially I expected that props are reactive, but they are not. Then I tried different ways to defender slider with updated options, but no luck.

**Comment by TitanFighter** [comment]
It seems `rebuild()` does not work as a standalone method, it just return a new instance of slider -> [Docs](https://github.com/ganlanyuan/tiny-slider#rebuild).

> rebuild
> Rebuild the slider after destroy.
> 
> slider = slider.rebuild();
> // this method returns a new slider Object with the same options with the original slider

**Comment by Suruat** [comment]
Yeah, that is a problem. As I worked with your plugin I discovered that all problems are coming from original tiny-slider. It just doesn't designed with reactivity in mind. Because of that I will probably create slider plugin for Vue from scratch when have free time. So don't bother with this topic and thank you :)

**Comment by TitanFighter** [comment]
@Suruat 
1. This is no my plugin :)
2. You can try `vue-aswesome-swiper`, but this component has 2 bugs which I found:
  - It seems that there could be just 1 instance at any time, which was not ok for me (if more than 1 -> it stops working properly).
  - It has a conflict with `vue-smooth-dnd`.

So, if you the above mentioned problems do not influence you, you can try it :)

**Comment by marekalgoud** [comment]
Hello,

This issue is old and closed but for those who are facing the same issue, I post my solution : 

- I had a data **loading** in my component.
- In my template, I had a `v-if=!loading` around the **vue-tiny-slider** component
- In the watcher, I add the following code (medias is my dynamic list of slides) : 
```
watch: {
    medias () {
      this.loading = true
      setTimeout(() => {
        this.loading = false
      }, 0)
    }
  }
```
=> This way, each time the medias is updated, the vue-tiny-slider is removed from the dom and reinserted with the new slides ! Works like a charm in my case (small sliders).
