### ISSUE TITLE
JSFiddle demonstration is broken

### ISSUE THREAD

**Issue by VitorLuizC** [viktorlarsson/vue-tiny-slider#28]

**Comment by TitanFighter** [comment]
Just double checked with Chrome and Firefox - everything is ok.
Here is the screen from Chrome

![image](https://user-images.githubusercontent.com/12687911/47288884-d499e680-d600-11e8-81ac-0f8b251d94f0.png)

I transferred the code to CodeSandbox - [please try](https://codesandbox.io/s/7m9w30xjz6).

**Comment by VitorLuizC** [comment]
This one is working nice!
