### ISSUE TITLE
Can't get the navContainer to work

### ISSUE THREAD

**Issue by tfdbloom** [viktorlarsson/vue-tiny-slider#43]
I'm trying to get navContainer to work but it seems as it cant find it. I tried the option of giving it this 

Here is a example on [codesandbox](https://codesandbox.io/s/23pkk425rj)

```
- navContainer: '#customize-thumbnails', 
- navContainer: document.querySelector('#customize-thumbnails'),
- navContainer: this.$refs.sliderThumbs, 
```

it does nothing. What could I be missing?

**Comment by viktorlarsson** [comment]
Closing this! Thanks for the help @JGriffCS
