### ISSUE TITLE
Unnecessary console logs

### ISSUE THREAD

**Issue by esl51** [viktorlarsson/vue-tiny-slider#51]
I have this in console:
```
{container: div.links-carousel__list, items: 1, mode: "carousel", gutter: 0, edgePadding: 0, …}
nav: false
controls: false
false
false
```
Can you, please, disable this behavior?

**Comment by vyarmolenko** [comment]
It seems that dist and source versions are different. There are no mentions of console in source and it is definitely in dist.

**Comment by viktorlarsson** [comment]
Sorry for the long delay, i've rebuilt into dist :)
