### ISSUE TITLE
Cannot target autoplay button or navcontainer with ID

### ISSUE THREAD

**Issue by danstans** [viktorlarsson/vue-tiny-slider#8]
I believe in tiny-slider you are able to target the autoplay button that says 'stop' and 'start' by using

"autoplayButton": "#customize-toggle"

However, you cannot use the ID selector inside a Vue prop; what is the recommended way to remove/modify the navcontainer and autoplay buttons?

**Comment by viktorlarsson** [comment]
Sorry for the late delay, had a kid so : -)

Have you tried the following?
"autoplayButton": document.getElementById("customize-toggle")

**Comment by viktorlarsson** [comment]
Did this work @danstans ?

**Comment by danstans** [comment]
Sorry, I am new to communicating on github. I didn't see these notifications, but I turned email notifications on now. Congratulations on your child by the way! I believe your suggestion should work, i'll give it a try tonight/tomorrow and get back to you. I'm quite busy with classes so it's been hard to find time to go back to the project I was using this package in.
